Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  CassandraSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      # A description for the security group
      # String
      GroupDescription: Allow ssh to/from our bastion host
      # The name of the security group
      # GroupName: String
      # The inbound rules associated with the security group
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0 # Change this to my IP Address
      # Any tags assigned to the security group
      #Tags: 
      #  - Tag
      # The ID of the VPC for the security group
      # String
      VpcId: 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"

  CassandraDB:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-003634241a8fcdec0 # Ubuntu
      # Ideally you want to only put the key during the time that you execute
      # this script. Remove it immediately after
      # Remember: If you push this, the key name will be public
      KeyName: cassandra-key
      SubnetId: 
        Fn::ImportValue:
          !Sub "${EnvironmentName}-PUB1-SN"
      SecurityGroupIds:
      - !Ref CassandraSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Install Docker
          sudo apt-get update && curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          docker pull dsalazar10/cassandra:master
          docker run -it --rm --name cassandra-node1 -p7000:7000 -p7001:7001 -p9042:9042 -p9160:9160 dsalazar10/cassandra:master

Outputs:
  CassandraAddress:
    Value: !GetAtt [CassandraDB, PublicIp]
    Description: Returns the Public IP Address for the database