Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  InstanceType:
    Description: Cluster's instance type hardware configuration
    Type: String

Resources:
  EMRCluster:
    DependsOn:
      - SparkServiceRole
      - SparkJobFlowRole
      - SparkLogBucket
    Type: AWS::EMR::Cluster
    Properties: 
      # AdditionalInfo: Json
      Applications: 
        - Name: Spark
        - Name: Hadoop
        - Name: Livy
      # AutoScalingRole: String
      # BootstrapActions: 
      #   - BootstrapActionConfig
      # Configurations: 
      #   - Configuration
      # CustomAmiId: String
      # EbsRootVolumeSize: Integer
      Instances: 
        # AdditionalMasterSecurityGroups: 
        #   - String
        # AdditionalSlaveSecurityGroups: 
        #   - String
        # CoreInstanceFleet: 
        #   InstanceFleetConfig
        CoreInstanceGroup: 
          # AutoScalingPolicy: 
          #   AutoScalingPolicy
          # BidPrice: String
          # Configurations:
          #   - Classification: hbase-site
          #     ConfigurationProperties: 
          #       hbase.rootdir : !Sub s3://${SparkLogBucket}/data
          #     Configurations:
          #     - Classification: hbase
          #       ConfigurationProperties:
          #         hbase.emr.storageMode: s3
          # EbsConfiguration: 
          #   EbsConfiguration
          InstanceCount: 3
          InstanceType: !Ref InstanceType
          # Market: String
          Name: core-group
        Ec2KeyName: spark-key 
        Ec2SubnetId:
          Fn::ImportValue:
            !Sub "${EnvironmentName}-PRI1-SN"
        # Ec2SubnetIds: 
        #   - String
        # EmrManagedMasterSecurityGroup: String
        # EmrManagedSlaveSecurityGroup: String
        # HadoopVersion: String
        # KeepJobFlowAliveWhenNoSteps: Boolean
        # MasterInstanceFleet: 
        #   InstanceFleetConfig
        MasterInstanceGroup: 
          # AutoScalingPolicy: 
          #   AutoScalingPolicy
          # BidPrice: String
          # Configurations: 
          #   - Configuration
          # EbsConfiguration: 
          #   EbsConfiguration
          InstanceCount: 1
          InstanceType: !Ref InstanceType
          # Market: String
          Name: master-group
        # Placement: 
        #   PlacementType
        # ServiceAccessSecurityGroup: String
        # TerminationProtected: Boolean
      JobFlowRole: !Ref SparkJobFlowProfile
      # KerberosAttributes: 
      #   KerberosAttributes
      LogUri: !Sub s3://${SparkLogBucket}/logs/
      Name: spark-udacity
      ReleaseLabel: emr-5.30.0
      # ScaleDownBehavior: String
      # SecurityConfiguration: String
      ServiceRole: !Ref SparkServiceRole
      # Steps: 
      #   - StepConfig
      # Tags: 
      #   - Tag
      # VisibleToAllUsers: Boolean

  SparkLogBucket:
      Type: AWS::S3::Bucket
  
  SparkJobFlowProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref SparkJobFlowRole
        
  SparkJobFlowRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role'

  SparkServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: elasticmapreduce.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole'

Outputs:
  MasterPublicDNS:
    Description: The public DNS name of the master node
    Value: !GetAtt [EMRCluster, MasterPublicDNS]
    Export:
      Name: !Sub ${EnvironmentName}-M-DNS
  LogBucketName:
      Value: !Ref SparkLogBucket
      Description: Name of the Amazon S3 bucket used to store log files.